containers: Cap sphinx at 7 to unblock CI.
Just released sphinx 8.0 requires Pygments >= 2.17, but it fails to
build with it in practice.  This breaks our CI completely:

  Traceback (most recent call last):
    File "/usr/local/bin/sphinx-build", line 5, in <module>
      from sphinx.cmd.build import main
    File "sphinx/cmd/build.py", line 21, in <module>
      from sphinx.application import Sphinx
    File "sphinx/application.py", line 29, in <module>
      from sphinx.highlighting import lexer_classes
    File "sphinx/highlighting.py", line 86, in <module>
      class PygmentsBridge:
      ...<131 lines>...
                  return formatter.get_style_defs() + _LATEX_ADD_STYLES
    File "sphinx/highlighting.py", line 89, in PygmentsBridge
      html_formatter = HtmlFormatter[str]
                       ~~~~~~~~~~~~~^^^^^
  TypeError: type 'HtmlFormatter' is not subscriptable

Cap the version for now to unblock CI.

Can be reverted once https://github.com/sphinx-doc/sphinx/issues/12711
is fixed.

Signed-off-by: Ilya Maximets <i.maximets@ovn.org>
Signed-off-by: 0-day Robot <robot@bytheb.org>