ci: Use user for pip upgrade on Ubuntu.
The pip upgrade in Ubuntu started to fail because of missing
RECORD file. Use the --user argument which avoids this error and
allows pip to upgrade itself.

ERROR: Cannot uninstall pip 24.0, RECORD file not found.
Hint: The package was installed by debian.

Suggested-by: Ilya Maximets <i.maximets@ovn.org>
Signed-off-by: Ales Musil <amusil@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>