Fix the compilation failures
Below compilation errors are seen:

- make[1]: *** No rule to make target 'Documentation/internals/charter.rst', needed by 'all-am'.  Stop.

- Warning, treated as error:
../MAINTAINERS.rst:63:Insufficient data supplied (1 row(s)); no data remaining for table body, required by "list-table" directive.

Fixes: 0ba67050dcb3("Remove the OVS charter.")
Fixes: 311b1a31ceb5(Acknowledge that OVN committers are a new group.)
CC: Russell Bryant <russell@ovn.org>
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>
Acked-by: Ben Pfaff <blp@ovn.org>
Acked-by: Russell Bryant <russell@ovn.org>
Signed-off-by: 0-day Robot <robot@bytheb.org>