expr: Prevent dangling pointer error
GCC 12 started to report the struct annotation_nesting
as dangling pointer because it is created on stack
and pushed to list. Disable the dangling pointer check
for this ovs_list_insert call.

In file included from /workspace/ovn/ovs/include/openvswitch/ofpbuf.h:25,
                 from /workspace/ovn/ovs/lib/tun-metadata.h:24,
                 from /workspace/ovn/ovs/lib/packets.h:32,
                 from /workspace/ovn/ovs/lib/flow.h:31,
                 from /workspace/ovn/ovs/lib/nx-match.h:24,
                 from lib/expr.c:20:
In function 'ovs_list_insert',
    inlined from 'ovs_list_push_back' at /workspace/ovn/ovs/include/openvswitch/list.h:205:5,
    inlined from 'expr_annotate_cmp' at lib/expr.c:1984:5,
    inlined from 'expr_annotate__' at lib/expr.c:2060:16:
/workspace/ovn/ovs/include/openvswitch/list.h:168:18: error: storing the address of local variable 'an' in '*nesting.prev' [-Werror=dangling-pointer=]
  168 |     before->prev = elem;
      |     ~~~~~~~~~~~~~^~~~~~
lib/expr.c: In function 'expr_annotate__':
lib/expr.c:1982:31: note: 'an' declared here
 1982 |     struct annotation_nesting an;
      |                               ^~
lib/expr.c:1982:31: note: 'nesting' declared here

Signed-off-by: Ales Musil <amusil@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>